#!/bin/bash

# dirs
CUR_DIR=$(pwd)
NP_DATA_DIR="$HOME"/.local/share/Next-Prayer
NP_CNFG_DIR="$HOME"/.config/Next-Prayer
NP_BINR_DIR="$HOME"/.local/bin

# do not change these parameters unless you live outside Egypt
# 5 - Egyptian General Authority of Survey
method="5"
month="1"
adjustment="1"
# If annual true, the month will be ignored and return the calendar for the whole year.
annual="true"

def_params() {
  echo "{" > "$NP_CNFG_DIR"/params.json
  { echo "  \"latitude\":\"$latitude\",";
    echo "  \"longitude\":\"$longitude\",";
    echo "  \"method\":\"$method\",";
    echo "  \"month\":\"$month\",";
    echo "  \"adjustment\":\"$adjustment\",";
    echo "  \"annual\":\"$annual\",";
    echo "  \"year\":\"$year\"";
    echo "}"; } >> "$NP_CNFG_DIR"/params.json
}

setup() {
  echo "Location setup:"
  echo "(hint: use https://www.google.com/maps/)"

  echo -n "Enter your location latitude (default = 30.052816227561923)[cairo]: "
  read latitude
  [ -z "$latitude" ] || [ -z $(echo -n "$latitude" | grep -E "^([0-9]+)\.([0-9]+)$") ] && latitude="30.052816227561923"

  echo -n "Enter your location longitude (default = 31.230651905820896)[cairo]: "
  read longitude
  [ -z "$longitude" ] || [ -z $(echo -n "$longitude" | grep -E "^([0-9]+)\.([0-9]+)$") ] && longitude="31.230651905820896"

  echo -n "Enter the year(default = 2021): "
  read year
  [ -z "$year" ] || [ -z $(echo -n "$year" | grep -E "^(20[0-9]{2})$") ] && year="2021"

  def_params
}

mkdir -p "$NP_DATA_DIR"/calendar/{1..12} && mkdir -p "$NP_CNFG_DIR" || exit 1
[[ -e "$NP_CNFG_DIR"/params.json ]] || setup

# fetch the whole year calendar
python3 "$CUR_DIR"/FetchWholeYear.py

# compile the cpp file
g++ "$CUR_DIR"/FindNextPrayer.cpp -o "$CUR_DIR"/FindNextPrayer

cp "$CUR_DIR"/NextPrayer "$NP_BINR_DIR"/NextPrayer
cp "$CUR_DIR"/FindNextPrayer "$NP_BINR_DIR"/FindNextPrayer
