#!/bin/bash

NP_DATA_DIR="$HOME"/.local/share/Next-Prayer/calendar
NP_TEMP_DIR=/tmp/Next-Prayer

fetch_next_day() {
  CUR_MONTH=$(date "+%_m" | gawk '{print $1}')
  CUR_DAY=$(date "+%_d" | gawk '{print $1}')

  mkdir -p "$NP_TEMP_DIR"

  # cached data processing
  cat "$NP_DATA_DIR/$CUR_MONTH/$CUR_DAY" | jq '.["timings"]' > "$NP_TEMP_DIR"/timings
  cat "$NP_DATA_DIR/$CUR_MONTH/$CUR_DAY" | jq '.["date"]' > "$NP_TEMP_DIR"/hijri

  sed -i "s/ (.*)\|\"\|{\|}\|,//g" "$NP_TEMP_DIR"/timings
  gawk -i inplace -F': ' 'NF {print $2 $1}' "$NP_TEMP_DIR"/timings


  sed -i "s/{\|}\|\"\|,\|\ //g; /^[^de].*$/d; /^\s*$/d; s/^.*://g; s/-..-/ /g" "$NP_TEMP_DIR"/hijri
  gawk -i inplace 'NR == 2 {print l "." $0 "." r} {l = $1; r = $2}' "$NP_TEMP_DIR"/hijri
}

get_output() {
  echo $(echo "$1" | gawk -F: '{hrs = $1; mod = hrs % 12; mer = "AM"; if(mod == 10 || mod == 0 || mod == 11) {
  if(hrs >= 12) mer = "PM"; if(hrs == 0) mod = 12; print mod ":" $2, mer;} else { print "0" mod ":" $2, mer}}')
}

! [[ -e "$NP_TEMP_DIR"/timings ]] || [  $(cat "$NP_TEMP_DIR"/timings | wc -l) -lt 8 ] && fetch_next_day

CUR_TIME=$(date "+%H:%M")

cat "$NP_TEMP_DIR"/timings > "$NP_TEMP_DIR"/input
echo "$CUR_TIME  A" >> "$NP_TEMP_DIR"/input

FindNextPrayer


NextTime=$(cat "$NP_TEMP_DIR"/output | gawk '/NextPrayer/ {print $2}')
When=$(cat "$NP_TEMP_DIR"/output | gawk '/NextPrayer/ {print $3}')
Remains=$(cat "$NP_TEMP_DIR"/output | gawk '/Remains/ {print $2}')
AdhanTime=$(cat "$NP_TEMP_DIR"/output | gawk '/AdhanTime/ {print $2}')
FetchNextDay=$(cat "$NP_TEMP_DIR"/output | gawk '/FetchNextDay/ {print $2}')

[[ $FetchNextDay -eq 1 ]] && fetch_next_day
[[ $AdhanTime -eq 1 ]] && notify-send "Next Prayer" "It's time for $NextTime"

case "$1" in
  "--rem") echo "$Remains";;
  "--adn") echo "$AdhanTime";;
  "--help"|"-h") printf "%s\n%s\t\t%s\n%s\t\t%s\n%s\t\t%s\n%s\t%s\n" "Next Prayer" "--rem" "Remaining time till the next prayer" "--nxt" "The name and the time for the next prayer" "--adn" "Is it time for adhan or not by returning binary value(0, 1)" "--help, -h" "Showing this info";;
  "--nxt"|*) echo "$NextTime $(get_output $When)";;
esac

case $BLOCK_BUTTON in
    1) notify-send "Next Prayer" "Time till $NextTime $Remains";;
esac
