#!/bin/bash

# Redirect to cpp file
np_main "$1"
if [[ "$1" = "--hijri" ]]; then
	exit 0
fi

if [[ "$(np_main --adhan)" = "True" ]]; then
	notify-send "Next Prayer" "Adhan time for $(np_main --next | awk '{print $1}') prayer"
fi

# Notify on click
case "${BUTTON}" in
	1)
		notify-send -t 60000 "Next Prayer" \
		  "$(printf "%s %s %s\n%s %s %s" "$(np_main --left)" \
			"until" "$(np_main --next)" \
			"$(np_main --elapsed)" "since" "$(np_main --prev)" \
			| awk 'BEGIN { printf "%-8s %-8s %s\n", "Time", "", "Salat";
			printf "%-8s %-8s %s\n", "-----", "", "-------" }
			{ printf "%-8s %-8s %s\n", $1, $2, $3 }')"
		;;
esac
