#!/bin/bash

# Redirect to cpp file
events "$1"
if [[ "$1" = "--hijri" ]]; then
	exit
fi

# Notify on click
case "${BLOCK_BUTTON}" in
	1)
		notify-send -t 60000 "Next Prayer" \
		"$(printf "%s %s %s\n%s %s %s" "$(events --left)" "until" "$(events --next)" \
			"$(events --elapsed)" "since" "$(events --prev)" \
			| awk 'BEGIN { printf "%-8s %-8s %s\n", "Time", "", "Salat";
			printf "%-8s %-8s %s\n", "-----", "", "-------" }
			{ printf "%-8s %-8s %s\n", $1, $2, $3 }')"
				;;
esac
