#!/bin/bash

NP_DATA_DIR="$HOME"/.local/share/Next-Prayer/calendar
NP_TEMP_DIR=/tmp/Next-Prayer
ICON="🕌"

case $BLOCK_BUTTON in
    1) notify-send "As-Salah" "The remaining time till $NextTime is $Remains";;
esac

fetch_next_day() {
  CUR_MONTH=$(date "+%_m" | awk '{print $1}')
  CUR_DAY=$(date "+%_d" | awk '{print $1}')

  mkdir -p "$NP_TEMP_DIR"

  # cached data processing
  cat "$NP_DATA_DIR/$CUR_MONTH/$CUR_DAY" | jq '.["timings"]' > "$NP_TEMP_DIR"/timings
  cat "$NP_DATA_DIR/$CUR_MONTH/$CUR_DAY" | jq '.["date"]' > "$NP_TEMP_DIR"/hijri

  sed -i "s/ (.*)\|\"\|{\|}\|,//g" "$NP_TEMP_DIR"/timings
  gawk -i inplace -F': ' 'NF {print $2 $1}' "$NP_TEMP_DIR"/timings


  sed -i "s/{\|}\|\"\|,\|\ //g; /^[^de].*$/d; /^\s*$/d; s/^.*://g; s/-..-/ /g" "$NP_TEMP_DIR"/hijri
  gawk -i inplace 'NR == 2 {print l "." $0 "." r} {l = $1; r = $2}' "$NP_TEMP_DIR"/hijri
}

get_output() {
  echo $(echo "$1" | awk -F: '{hrs = $1; mod = hrs % 12; mer = "AM"; if(mod == 10 || mod == 0 || mod == 11) {
  if(hrs >= 12) mer = "PM"; if(hrs == 0) hrs = 12; print hrs ":" $2, mer;} else { print "0" mod ":" $2, mer}}')
}

! [[ -e "$NP_TEMP_DIR"/timings ]] && fetch_next_day

CUR_TIME=$(date "+%H:%M")

cat "$NP_TEMP_DIR"/timings > "$NP_TEMP_DIR"/input
echo "$CUR_TIME  A" >> "$NP_TEMP_DIR"/input
FindNextPrayer < "$NP_TEMP_DIR"/input

[ -z "$NP_TEMP_DIR"/output ] && exit 1

NextTime=$(cat "$NP_TEMP_DIR"/output | awk '/NextPrayer/ {print $2}')
When=$(cat "$NP_TEMP_DIR"/output | awk '/NextPrayer/ {print $3}')
Remains=$(cat "$NP_TEMP_DIR"/output | awk '/Remains/ {print $2}')
AdhanTime=$(cat "$NP_TEMP_DIR"/output | awk '/AdhanTime/ {print $2}')
FetchNextDay=$(cat "$NP_TEMP_DIR"/output | awk '/FetchNextDay/ {print $2}')

[[ $FetchNextDay -eq 1 ]] && fetch_next_day
[[ $AdhanTime -eq 1 ]] && notify-send "As-Salah" "It's time for $NextTime"

echo "$ICON $NextTime $(get_output $When)"
