#!/bin/bash

NP_TEMP_DIR=/tmp/Next-Prayer

! [[ -e "$NP_TEMP_DIR"/timings ]] && FetchNextDay

ICON="🕌"

CUR_TIME=$(date "+%H:%M")

cat "$NP_TEMP_DIR"/timings > "$NP_TEMP_DIR"/input
echo "$CUR_TIME  A" >> "$NP_TEMP_DIR"/input
FindNextPrayer < "$NP_TEMP_DIR"/input

NextTime=$(cat "$NP_TEMP_DIR"/output | awk '/NextPrayer/ {print $2}')
When=$(cat "$NP_TEMP_DIR"/output | awk '/NextPrayer/ {print $3}')
Remains=$(cat "$NP_TEMP_DIR"/output | awk '/Remains/ {print $2}')
AdhanTime=$(cat "$NP_TEMP_DIR"/output | awk '/AdhanTime/ {print $2}')
FetchNextDay=$(cat "$NP_TEMP_DIR"/output | awk '/FetchNextDay/ {print $2}')

[[ $FetchNextDay -eq 1 ]] && FetchNextDay
[[ $AdhanTime -eq 1 ]] && notify-send "As-Salah" "It's the time for $NextTime"

echo "$ICON $NextTime $When"
