.TH NXPRAYER 1 2021-09-28 GNU

.SH
NAME
nxprayer \- Next Islamic prayer time

.SH
SYNOPSIS
.B
nxprayer
[\fB\-h\fR]

.B
nxprayer
[\fB\-n\fR]

.B
nxprayer
[\fB\-r\fR]

.B
nxprayer
[\fB\-d\fR]

.SH
DESCRIBTION
.B
nxprayer
displaya the time of the next Islamic prayer.

.SH
OPTIONS
.TP
.BR \-h ", " \-\-help
display this help information.
.TP
.BR \-n ", " \-\-next
display the time of the next islamic prayer.
.TP
.BR \-r ", " \-\-remain
display the remaining time till the next prayer.
.TP
.BR \-d ", " \-\-adhan
display if it's time for adhan or not by returning binary value(0, 1).

.SH
FILES
.TP
.I ~/.local/bin/nxprayer
.TP
.I ~/.local/bin/lapi
.TP
.I ~/.config/nxprayer/params.json

.SH
AUTHOR
Abd El-Twab M. Fakhry <abdeltwab.m.fakhry@gmail.com>
